name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tatooi/local-alpine:latest
    - run: echo $PAT | docker login ghcr.io --username phanatic --password-stdin
    - run: docker push ghcr.io/tatooi/local-alpine:latest
